services:
  melody_backend:
    image: erbidium/melody_backend
    restart: on-failure
    ports:
        - "5050:5050"
    networks:
        - localnet
    environment:
        ASPNETCORE_ENVIRONMENT: 'Development'
        ConnectionStrings__MelodyDBConnection: "Server=sql_server;Database=MelodyDb;User=sa;Password=TestPassword!"
        ConnectionStrings__MasterConnection: "Server=sql_server;Database=master;User=sa;Password=TestPassword!"
        ELKConfiguration__url: "http://elasticsearch:9200"
        Jwt__Issuer: "https://localhost:5050"
        Jwt__Audience: "https://localhost:5050"
        TZ: "Europe/Kiev"

  melody_frontend:
    depends_on:
        - melody_backend
    image: erbidium/melody_frontend
    restart: on-failure
    ports:
        - "4200:80"
    environment:
        BACKEND_BASE_URL: http://localhost:5050
        STATISTICS_BASE_URL: http://localhost:3000/public-dashboards/ce5cf4e4d9554c00ac4e9506a2e42416
    networks:
        - localnet
        - front

networks:
    localnet:
        driver: bridge
    front:
        driver: bridge