{
 "title": "Music statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Popular songs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "MelodyDb",
     "rawSql": "SELECT TOP 10 Name, COUNT(ListeningStatistics.SongId) as ListeningCount\r\nFROM ListeningStatistics\r\nINNER JOIN Songs ON Songs.Id = ListeningStatistics.SongId\r\nGROUP BY ListeningStatistics.SongId, Name\r\nORDER BY ListeningCount DESC;"
    }
   ]
  },
  {
   "title": "Popular genres",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT TOP 10 Genres.Name, COUNT(ListeningStatistics.SongId) as ListeningCount\r\nFROM ListeningStatistics\r\nINNER JOIN Songs ON Songs.Id = ListeningStatistics.SongId\r\nINNER JOIN Genres ON Songs.GenreId = Genres.Id\r\nGROUP BY Genres.Name, GenreId\r\nORDER BY ListeningCount DESC;"
    }
   ]
  },
  {
   "title": "Popular authors",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT TOP 10 Songs.AuthorName, COUNT(ListeningStatistics.SongId) as ListeningCount\r\nFROM ListeningStatistics\r\nINNER JOIN Songs ON Songs.Id = ListeningStatistics.SongId\r\nGROUP BY Songs.AuthorName\r\nORDER BY ListeningCount DESC;"
    }
   ]
  }
 ]
}