name: Code Analysis
on:
  push:
    branches: [ development ]
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build frontend docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./frontend/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/melody_frontend:latest
          outputs: type=docker,dest=/tmp/melody_frontend.tar

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: melody_frontend
          path: /tmp/melody_frontend.tar

      - name: Build backend docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./backend/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/melody_backend:latest
          outputs: type=docker,dest=/tmp/melody_backend.tar

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: melody_backend
          path: /tmp/melody_backend.tar

  push-docker-images:
    needs: build-docker-images
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: melody_frontend
          path: /tmp
      
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: melody_backend
          path: /tmp

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load backend docker image
        run: docker load --input /tmp/melody_backend.tar

      - name: Load frontend docker image
        run: docker load --input /tmp/melody_frontend.tar

      - name: Push frontend docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/melody_frontend

      - name: Push backend docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/melody_backend

  